//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UskudarDenetim.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circular
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
    }
}
