//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UskudarDenetim.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSocialMedia
    {
        public System.Guid Id { get; set; }
        public System.Guid SocialMediaId { get; set; }
        public System.Guid ContactId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual SocialMedia SocialMedia { get; set; }
    }
}
