//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UskudarDenetim.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.ContactSocialMedias = new HashSet<ContactSocialMedia>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<long> LocalePhoneNumber { get; set; }
        public Nullable<long> FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string EmailAddress2 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactSocialMedia> ContactSocialMedias { get; set; }
    }
}
